"""empty message

Revision ID: b27d2eec319d
Revises: 
Create Date: 2020-04-04 16:18:03.814674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27d2eec319d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dat', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(length=20), nullable=False),
    sa.Column('short', sa.Text(length=50), nullable=False),
    sa.Column('breif', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blog')
    # ### end Alembic commands ###
